FROM maven:3.9.9-eclipse-temurin-21-alpine AS build
WORKDIR /app
COPY pom.xml .
COPY src ./src
RUN mvn clean package

FROM openjdk:17-jre-slim
WORKDIR /app
COPY --from=build /app/target/card-game.jar /app/card-game.jar
ENTRYPOINT ["java", "-jar", "/app/card-game.jar"]